"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type SaleRow={suburb:string;postcode:string;sale_month:string;sale_count:number|string;median_price_aud:number|string|null;average_price_aud:number|string|null;minimum_price_aud:number|string|null;maximum_price_aud:number|string|null};
type Suburb={suburb:string;postcode:string;sale_count:number|string};
const money=new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0});const number=new Intl.NumberFormat("en-AU");
export default function SalesExplorer(){const [suburbs,setSuburbs]=useState<Suburb[]>([]),[suburb,setSuburb]=useState("Yokine|6060"),[from,setFrom]=useState("2000-01-01"),[to,setTo]=useState("2026-12-31"),[rows,setRows]=useState<SaleRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{fetch("/api/analytics/suburbs").then(r=>r.json()).then(j=>setSuburbs(j.data)).catch(()=>setError("Suburb index is temporarily unavailable."));},[]);
async function load(event?:FormEvent){event?.preventDefault();setLoading(true);setError("");const [name,postcode]=suburb.split("|");try{const q=new URLSearchParams({suburb:name,postcode,from,to,limit:"1200"});const response=await fetch(`/api/analytics/suburb-sales?${q}`);if(!response.ok)throw new Error();const json=await response.json();setRows(json.data.slice().reverse());}catch{setError("The analytical service did not respond. Please try again.");}finally{setLoading(false);}}
useEffect(()=>{const q=new URLSearchParams({suburb:"Yokine",postcode:"6060",from:"2000-01-01",to:"2026-12-31",limit:"1200"});fetch(`/api/analytics/suburb-sales?${q}`).then(response=>{if(!response.ok)throw new Error();return response.json();}).then(json=>setRows(json.data.slice().reverse())).catch(()=>setError("The analytical service did not respond. Please try again.")).finally(()=>setLoading(false));},[]);
const metrics=useMemo(()=>{const priced=rows.filter(r=>r.median_price_aud!=null),latest=priced.at(-1),prior=priced.length>12?priced.at(-13):priced[0],total=rows.reduce((sum,r)=>sum+Number(r.sale_count),0),change=latest&&prior?((Number(latest.median_price_aud)/Number(prior.median_price_aud)-1)*100):null;return{latest,total,change,months:rows.length};},[rows]);
function download(){const header=Object.keys(rows[0]||{});const csv=[header.join(","),...rows.map(row=>header.map(key=>JSON.stringify(String(row[key as keyof SaleRow]??""))).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${suburb.split("|")[0].toLowerCase().replaceAll(" ","-")}-sales.csv`;a.click();URL.revokeObjectURL(a.href);}
return <section className="explorer" aria-label="Property sales explorer"><form className="filters" onSubmit={load}><label>Suburb<select value={suburb} onChange={e=>setSuburb(e.target.value)}>{suburbs.length?suburbs.map(s=><option key={`${s.suburb}|${s.postcode}`} value={`${s.suburb}|${s.postcode}`}>{s.suburb} · {s.postcode}</option>):<option>Yokine|6060</option>}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="submit">Run analysis</button></form>{error&&<p className="error" role="alert">{error}</p>}<div className="kpis" aria-busy={loading}><article><span>Latest median</span><strong>{loading?"—":metrics.latest?money.format(Number(metrics.latest.median_price_aud)):"Not available"}</strong><small>{metrics.latest?new Date(metrics.latest.sale_month).toLocaleDateString("en-AU",{month:"long",year:"numeric"}):""}</small></article><article><span>12-month movement</span><strong className={(metrics.change??0)>=0?"positive":"negative"}>{loading||metrics.change==null?"—":`${metrics.change>=0?"+":""}${metrics.change.toFixed(1)}%`}</strong><small>Median price comparison</small></article><article><span>Recorded sales</span><strong>{loading?"—":number.format(metrics.total)}</strong><small>{metrics.months} monthly observations</small></article></div><div className="chart-grid"><Chart title="Median sale price" rows={rows} value={r=>Number(r.median_price_aud||0)} format={v=>money.format(v)} loading={loading}/><Chart title="Monthly sale volume" rows={rows} value={r=>Number(r.sale_count)} format={v=>number.format(v)} bars loading={loading}/></div><div className="data-footer"><p>Monthly aggregates · Source: realestate.com.au observations · Query engine: MotherDuck</p><button type="button" onClick={download} disabled={!rows.length}>Download CSV</button></div></section>;}
function Chart({title,rows,value,format,bars=false,loading}:{title:string;rows:SaleRow[];value:(r:SaleRow)=>number;format:(v:number)=>string;bars?:boolean;loading:boolean}){const width=800,height=260,pad=36,values=rows.map(value),max=Math.max(...values,1),points=values.map((v,i)=>`${pad+(i/Math.max(values.length-1,1))*(width-pad*2)},${height-pad-(v/max)*(height-pad*2)}`).join(" ");return <figure><figcaption><span>{title}</span><strong>{rows.length?format(values.at(-1)||0):"—"}</strong></figcaption><div className="chart">{loading?<div className="skeleton"/>:<svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title} over time`} preserveAspectRatio="none"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/>{bars?values.map((v,i)=>{const w=(width-pad*2)/Math.max(values.length,1),h=(v/max)*(height-pad*2);return <rect key={i} x={pad+i*w} y={height-pad-h} width={Math.max(w-.5,1)} height={h}/>;}):<polyline points={points}/>}</svg>}</div><small>{rows[0]?new Date(rows[0].sale_month).getFullYear():""}<span>{rows.at(-1)?new Date(rows.at(-1)!.sale_month).getFullYear():""}</span></small></figure>;}
